services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    container_name: RetentionAI_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: retention
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../RetentionAI_Backend
    container_name: RetentionAI_backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:0000@postgres:5432/retention
      JWT_SECRET_KEY: sedflkn54zmelfk56ze
      JWT_ALGORITHM: HS256
      GENAI_API_KEY: "AIzaSyDlDhNA0XPd4M_s-eZ8LBQWXfNneAWejw4"  
    depends_on:
      - postgres

  frontend:
    build:
      context: .
    container_name: RetentionAI_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: